### ISSUE TITLE
Issue with authentication

### ISSUE THREAD

**Issue by gimife** [Vrekt/Athena#19]
There seems to be an issue with the **FortniteAuthenticator** class
`javax.naming.AuthenticationException: Failed to retrieve cookies.
        at athena.authentication.FortniteAuthenticator.authenticate(FortniteAuthenticator.java:63)
        at com.fnranked.athena.AthenaImpl.login(AthenaImpl.java:92)`

I was able to fix it by saving all cookies from the https://www.epicgames.com/id/api/csrf response and putting them in the https://www.epicgames.com/id/api/login request.

**Comment by Vrekt** [comment]
Yeah, I need to change to using a cookie jar so everything could be simplified. With that being said this project is pretty inactive and there are a few issues that need to be addressed. I started a new version of Athena but I'm only working on it in my free time so its going pretty slow (I'm also really burned out). If you wish to have a newer authentication class I have written a newer one (which also now supports 2FA).

https://hastebin.com/utefiratut.php

Some things may need to be replaced like the `JsonFind` class and maybe some `ResponseConsumer` methods since these are new.
